// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: workload_identity.proto

package mwlid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWorkloadTrustBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadTrustBundlesRequest) Reset() {
	*x = GetWorkloadTrustBundlesRequest{}
	mi := &file_workload_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadTrustBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadTrustBundlesRequest) ProtoMessage() {}

func (x *GetWorkloadTrustBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadTrustBundlesRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadTrustBundlesRequest) Descriptor() ([]byte, []int) {
	return file_workload_identity_proto_rawDescGZIP(), []int{0}
}

type GetWorkloadTrustBundlesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The json formatted collection of SPIFFE trust bundles object represented as
	// a JWK Set and keyed by the trust domain name as described in
	// https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Trust_Domain_and_Bundle.md
	SpiffeTrustBundlesMapJson []byte `protobuf:"bytes,1,opt,name=spiffe_trust_bundles_map_json,json=spiffeTrustBundlesMapJson,proto3" json:"spiffe_trust_bundles_map_json,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetWorkloadTrustBundlesResponse) Reset() {
	*x = GetWorkloadTrustBundlesResponse{}
	mi := &file_workload_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadTrustBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadTrustBundlesResponse) ProtoMessage() {}

func (x *GetWorkloadTrustBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadTrustBundlesResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadTrustBundlesResponse) Descriptor() ([]byte, []int) {
	return file_workload_identity_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkloadTrustBundlesResponse) GetSpiffeTrustBundlesMapJson() []byte {
	if x != nil {
		return x.SpiffeTrustBundlesMapJson
	}
	return nil
}

type GetWorkloadCertificatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadCertificatesRequest) Reset() {
	*x = GetWorkloadCertificatesRequest{}
	mi := &file_workload_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadCertificatesRequest) ProtoMessage() {}

func (x *GetWorkloadCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadCertificatesRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_workload_identity_proto_rawDescGZIP(), []int{2}
}

type GetWorkloadCertificatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The PEM-encoded certificate chain ordered from leaf to root,
	// excluding the root.
	//
	// The leaf certificate is an SVID that contains a SPIFFE id in the URI SAN.
	// Each subsequent certificate will be an intermediate certificate that signs
	// the preceding certificate.
	CertificateChainPem []byte `protobuf:"bytes,1,opt,name=certificate_chain_pem,json=certificateChainPem,proto3" json:"certificate_chain_pem,omitempty"`
	// The PEM-encoded private key corresponding to the leaf certificate in the
	// certificate chain.
	PrivateKeyPem []byte `protobuf:"bytes,2,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadCertificatesResponse) Reset() {
	*x = GetWorkloadCertificatesResponse{}
	mi := &file_workload_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadCertificatesResponse) ProtoMessage() {}

func (x *GetWorkloadCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadCertificatesResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_workload_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkloadCertificatesResponse) GetCertificateChainPem() []byte {
	if x != nil {
		return x.CertificateChainPem
	}
	return nil
}

func (x *GetWorkloadCertificatesResponse) GetPrivateKeyPem() []byte {
	if x != nil {
		return x.PrivateKeyPem
	}
	return nil
}

var File_workload_identity_proto protoreflect.FileDescriptor

const file_workload_identity_proto_rawDesc = "" +
	"\n" +
	"\x17workload_identity.proto\x12\"managed_workload_identity.proto.v1\" \n" +
	"\x1eGetWorkloadTrustBundlesRequest\"c\n" +
	"\x1fGetWorkloadTrustBundlesResponse\x12@\n" +
	"\x1dspiffe_trust_bundles_map_json\x18\x01 \x01(\fR\x19spiffeTrustBundlesMapJson\" \n" +
	"\x1eGetWorkloadCertificatesRequest\"}\n" +
	"\x1fGetWorkloadCertificatesResponse\x122\n" +
	"\x15certificate_chain_pem\x18\x01 \x01(\fR\x13certificateChainPem\x12&\n" +
	"\x0fprivate_key_pem\x18\x02 \x01(\fR\rprivateKeyPem2\xe0\x02\n" +
	"\x10WorkloadIdentity\x12\xa4\x01\n" +
	"\x17GetWorkloadTrustBundles\x12B.managed_workload_identity.proto.v1.GetWorkloadTrustBundlesRequest\x1aC.managed_workload_identity.proto.v1.GetWorkloadTrustBundlesResponse\"\x00\x12\xa4\x01\n" +
	"\x17GetWorkloadCertificates\x12B.managed_workload_identity.proto.v1.GetWorkloadCertificatesRequest\x1aC.managed_workload_identity.proto.v1.GetWorkloadCertificatesResponse\"\x00B\x02P\x01b\x06proto3"

var (
	file_workload_identity_proto_rawDescOnce sync.Once
	file_workload_identity_proto_rawDescData []byte
)

func file_workload_identity_proto_rawDescGZIP() []byte {
	file_workload_identity_proto_rawDescOnce.Do(func() {
		file_workload_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workload_identity_proto_rawDesc), len(file_workload_identity_proto_rawDesc)))
	})
	return file_workload_identity_proto_rawDescData
}

var file_workload_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_workload_identity_proto_goTypes = []any{
	(*GetWorkloadTrustBundlesRequest)(nil),  // 0: managed_workload_identity.proto.v1.GetWorkloadTrustBundlesRequest
	(*GetWorkloadTrustBundlesResponse)(nil), // 1: managed_workload_identity.proto.v1.GetWorkloadTrustBundlesResponse
	(*GetWorkloadCertificatesRequest)(nil),  // 2: managed_workload_identity.proto.v1.GetWorkloadCertificatesRequest
	(*GetWorkloadCertificatesResponse)(nil), // 3: managed_workload_identity.proto.v1.GetWorkloadCertificatesResponse
}
var file_workload_identity_proto_depIdxs = []int32{
	0, // 0: managed_workload_identity.proto.v1.WorkloadIdentity.GetWorkloadTrustBundles:input_type -> managed_workload_identity.proto.v1.GetWorkloadTrustBundlesRequest
	2, // 1: managed_workload_identity.proto.v1.WorkloadIdentity.GetWorkloadCertificates:input_type -> managed_workload_identity.proto.v1.GetWorkloadCertificatesRequest
	1, // 2: managed_workload_identity.proto.v1.WorkloadIdentity.GetWorkloadTrustBundles:output_type -> managed_workload_identity.proto.v1.GetWorkloadTrustBundlesResponse
	3, // 3: managed_workload_identity.proto.v1.WorkloadIdentity.GetWorkloadCertificates:output_type -> managed_workload_identity.proto.v1.GetWorkloadCertificatesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workload_identity_proto_init() }
func file_workload_identity_proto_init() {
	if File_workload_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workload_identity_proto_rawDesc), len(file_workload_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workload_identity_proto_goTypes,
		DependencyIndexes: file_workload_identity_proto_depIdxs,
		MessageInfos:      file_workload_identity_proto_msgTypes,
	}.Build()
	File_workload_identity_proto = out.File
	file_workload_identity_proto_goTypes = nil
	file_workload_identity_proto_depIdxs = nil
}
