// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: workload_identity.proto

package mwlid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWorkloadTrustBundlesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWorkloadTrustBundlesRequest) Reset() {
	*x = GetWorkloadTrustBundlesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workload_identity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkloadTrustBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadTrustBundlesRequest) ProtoMessage() {}

func (x *GetWorkloadTrustBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_identity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadTrustBundlesRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadTrustBundlesRequest) Descriptor() ([]byte, []int) {
	return file_workload_identity_proto_rawDescGZIP(), []int{0}
}

type GetWorkloadTrustBundlesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The json formatted collection of SPIFFE trust bundles object represented as
	// a JWK Set and keyed by the trust domain name as described in
	// https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Trust_Domain_and_Bundle.md
	SpiffeTrustBundlesMapJson []byte `protobuf:"bytes,1,opt,name=spiffe_trust_bundles_map_json,json=spiffeTrustBundlesMapJson,proto3" json:"spiffe_trust_bundles_map_json,omitempty"`
}

func (x *GetWorkloadTrustBundlesResponse) Reset() {
	*x = GetWorkloadTrustBundlesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workload_identity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkloadTrustBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadTrustBundlesResponse) ProtoMessage() {}

func (x *GetWorkloadTrustBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_identity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadTrustBundlesResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadTrustBundlesResponse) Descriptor() ([]byte, []int) {
	return file_workload_identity_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkloadTrustBundlesResponse) GetSpiffeTrustBundlesMapJson() []byte {
	if x != nil {
		return x.SpiffeTrustBundlesMapJson
	}
	return nil
}

type GetWorkloadCertificatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWorkloadCertificatesRequest) Reset() {
	*x = GetWorkloadCertificatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workload_identity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkloadCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadCertificatesRequest) ProtoMessage() {}

func (x *GetWorkloadCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workload_identity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadCertificatesRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_workload_identity_proto_rawDescGZIP(), []int{2}
}

type GetWorkloadCertificatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The PEM-encoded certificate chain ordered from leaf to root,
	// excluding the root.
	//
	// The leaf certificate is an SVID that contains a SPIFFE id in the URI SAN.
	// Each subsequent certificate will be an intermediate certificate that signs
	// the preceding certificate.
	CertificateChainPem []byte `protobuf:"bytes,1,opt,name=certificate_chain_pem,json=certificateChainPem,proto3" json:"certificate_chain_pem,omitempty"`
	// The PEM-encoded private key corresponding to the leaf certificate in the
	// certificate chain.
	PrivateKeyPem []byte `protobuf:"bytes,2,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"`
}

func (x *GetWorkloadCertificatesResponse) Reset() {
	*x = GetWorkloadCertificatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workload_identity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkloadCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadCertificatesResponse) ProtoMessage() {}

func (x *GetWorkloadCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workload_identity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadCertificatesResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_workload_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkloadCertificatesResponse) GetCertificateChainPem() []byte {
	if x != nil {
		return x.CertificateChainPem
	}
	return nil
}

func (x *GetWorkloadCertificatesResponse) GetPrivateKeyPem() []byte {
	if x != nil {
		return x.PrivateKeyPem
	}
	return nil
}

var File_workload_identity_proto protoreflect.FileDescriptor

var file_workload_identity_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0x20, 0x0a,
	0x1e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x72, 0x75, 0x73,
	0x74, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x63, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x72,
	0x75, 0x73, 0x74, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x1d, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x5f, 0x74, 0x72, 0x75,
	0x73, 0x74, 0x5f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x19, 0x73, 0x70, 0x69, 0x66, 0x66,
	0x65, 0x54, 0x72, 0x75, 0x73, 0x74, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x4d, 0x61, 0x70,
	0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7d, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x63, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x70,
	0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x65, 0x6d, 0x12, 0x26, 0x0a,
	0x0f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x65, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x50, 0x65, 0x6d, 0x32, 0xe0, 0x02, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0xa4, 0x01, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x72, 0x75, 0x73, 0x74, 0x42,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12, 0x42, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64,
	0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x72, 0x75, 0x73, 0x74, 0x42, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x43, 0x2e, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x72, 0x75, 0x73, 0x74,
	0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0xa4, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x12, 0x42, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x43, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x5f, 0x77, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x02, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workload_identity_proto_rawDescOnce sync.Once
	file_workload_identity_proto_rawDescData = file_workload_identity_proto_rawDesc
)

func file_workload_identity_proto_rawDescGZIP() []byte {
	file_workload_identity_proto_rawDescOnce.Do(func() {
		file_workload_identity_proto_rawDescData = protoimpl.X.CompressGZIP(file_workload_identity_proto_rawDescData)
	})
	return file_workload_identity_proto_rawDescData
}

var file_workload_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_workload_identity_proto_goTypes = []interface{}{
	(*GetWorkloadTrustBundlesRequest)(nil),  // 0: managed_workload_identity.proto.v1.GetWorkloadTrustBundlesRequest
	(*GetWorkloadTrustBundlesResponse)(nil), // 1: managed_workload_identity.proto.v1.GetWorkloadTrustBundlesResponse
	(*GetWorkloadCertificatesRequest)(nil),  // 2: managed_workload_identity.proto.v1.GetWorkloadCertificatesRequest
	(*GetWorkloadCertificatesResponse)(nil), // 3: managed_workload_identity.proto.v1.GetWorkloadCertificatesResponse
}
var file_workload_identity_proto_depIdxs = []int32{
	0, // 0: managed_workload_identity.proto.v1.WorkloadIdentity.GetWorkloadTrustBundles:input_type -> managed_workload_identity.proto.v1.GetWorkloadTrustBundlesRequest
	2, // 1: managed_workload_identity.proto.v1.WorkloadIdentity.GetWorkloadCertificates:input_type -> managed_workload_identity.proto.v1.GetWorkloadCertificatesRequest
	1, // 2: managed_workload_identity.proto.v1.WorkloadIdentity.GetWorkloadTrustBundles:output_type -> managed_workload_identity.proto.v1.GetWorkloadTrustBundlesResponse
	3, // 3: managed_workload_identity.proto.v1.WorkloadIdentity.GetWorkloadCertificates:output_type -> managed_workload_identity.proto.v1.GetWorkloadCertificatesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workload_identity_proto_init() }
func file_workload_identity_proto_init() {
	if File_workload_identity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workload_identity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkloadTrustBundlesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workload_identity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkloadTrustBundlesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workload_identity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkloadCertificatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workload_identity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkloadCertificatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workload_identity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workload_identity_proto_goTypes,
		DependencyIndexes: file_workload_identity_proto_depIdxs,
		MessageInfos:      file_workload_identity_proto_msgTypes,
	}.Build()
	File_workload_identity_proto = out.File
	file_workload_identity_proto_rawDesc = nil
	file_workload_identity_proto_goTypes = nil
	file_workload_identity_proto_depIdxs = nil
}
