//  Copyright 2023 Google LLC
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distrbuted under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: guest_credentials.proto

package credentials

import (
	tpm "github.com/google/go-tpm-tools/proto/tpm"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A server response containing client credentials.
type GuestCredentialsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EncryptedCredentials []byte                 `protobuf:"bytes,1,opt,name=encrypted_credentials,json=encryptedCredentials,proto3" json:"encrypted_credentials,omitempty"`
	KeyImportBlob        *tpm.ImportBlob        `protobuf:"bytes,2,opt,name=key_import_blob,json=keyImportBlob,proto3" json:"key_import_blob,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GuestCredentialsResponse) Reset() {
	*x = GuestCredentialsResponse{}
	mi := &file_guest_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestCredentialsResponse) ProtoMessage() {}

func (x *GuestCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GuestCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_guest_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *GuestCredentialsResponse) GetEncryptedCredentials() []byte {
	if x != nil {
		return x.EncryptedCredentials
	}
	return nil
}

func (x *GuestCredentialsResponse) GetKeyImportBlob() *tpm.ImportBlob {
	if x != nil {
		return x.KeyImportBlob
	}
	return nil
}

var File_guest_credentials_proto protoreflect.FileDescriptor

const file_guest_credentials_proto_rawDesc = "" +
	"\n" +
	"\x17guest_credentials.proto\x12\x17agentcrypto.credentials\x1a\x1cgo-tpm-tools/proto/tpm.proto\"\x88\x01\n" +
	"\x18GuestCredentialsResponse\x123\n" +
	"\x15encrypted_credentials\x18\x01 \x01(\fR\x14encryptedCredentials\x127\n" +
	"\x0fkey_import_blob\x18\x02 \x01(\v2\x0f.tpm.ImportBlobR\rkeyImportBlobB\x0eZ\f/credentialsb\x06proto3"

var (
	file_guest_credentials_proto_rawDescOnce sync.Once
	file_guest_credentials_proto_rawDescData []byte
)

func file_guest_credentials_proto_rawDescGZIP() []byte {
	file_guest_credentials_proto_rawDescOnce.Do(func() {
		file_guest_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guest_credentials_proto_rawDesc), len(file_guest_credentials_proto_rawDesc)))
	})
	return file_guest_credentials_proto_rawDescData
}

var file_guest_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_guest_credentials_proto_goTypes = []any{
	(*GuestCredentialsResponse)(nil), // 0: agentcrypto.credentials.GuestCredentialsResponse
	(*tpm.ImportBlob)(nil),           // 1: tpm.ImportBlob
}
var file_guest_credentials_proto_depIdxs = []int32{
	1, // 0: agentcrypto.credentials.GuestCredentialsResponse.key_import_blob:type_name -> tpm.ImportBlob
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_guest_credentials_proto_init() }
func file_guest_credentials_proto_init() {
	if File_guest_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guest_credentials_proto_rawDesc), len(file_guest_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guest_credentials_proto_goTypes,
		DependencyIndexes: file_guest_credentials_proto_depIdxs,
		MessageInfos:      file_guest_credentials_proto_msgTypes,
	}.Build()
	File_guest_credentials_proto = out.File
	file_guest_credentials_proto_goTypes = nil
	file_guest_credentials_proto_depIdxs = nil
}
