// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: network_stats_report.proto

package network_stats_report

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Not used directly - provides mappings for `metrics` in `MetricsGroup`
type MetricId int32

const (
	MetricId_METRIC_ID_UNSPECIFIED MetricId = 0
	MetricId_RX_PACKETS            MetricId = 1
	MetricId_TX_PACKETS            MetricId = 2
	MetricId_RX_BYTES              MetricId = 3
	MetricId_TX_BYTES              MetricId = 4
	MetricId_LINK_DETECTED         MetricId = 5
	MetricId_DRIVER_VERSION        MetricId = 6
	MetricId_PACKET_DROPPED        MetricId = 7
	MetricId_AGENT_STARTED         MetricId = 8
	MetricId_KERNEL_VERSION        MetricId = 9
)

// Enum value maps for MetricId.
var (
	MetricId_name = map[int32]string{
		0: "METRIC_ID_UNSPECIFIED",
		1: "RX_PACKETS",
		2: "TX_PACKETS",
		3: "RX_BYTES",
		4: "TX_BYTES",
		5: "LINK_DETECTED",
		6: "DRIVER_VERSION",
		7: "PACKET_DROPPED",
		8: "AGENT_STARTED",
		9: "KERNEL_VERSION",
	}
	MetricId_value = map[string]int32{
		"METRIC_ID_UNSPECIFIED": 0,
		"RX_PACKETS":            1,
		"TX_PACKETS":            2,
		"RX_BYTES":              3,
		"TX_BYTES":              4,
		"LINK_DETECTED":         5,
		"DRIVER_VERSION":        6,
		"PACKET_DROPPED":        7,
		"AGENT_STARTED":         8,
		"KERNEL_VERSION":        9,
	}
)

func (x MetricId) Enum() *MetricId {
	p := new(MetricId)
	*p = x
	return p
}

func (x MetricId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricId) Descriptor() protoreflect.EnumDescriptor {
	return file_network_stats_report_proto_enumTypes[0].Descriptor()
}

func (MetricId) Type() protoreflect.EnumType {
	return &file_network_stats_report_proto_enumTypes[0]
}

func (x MetricId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Not used directly - provides mappings for `source` in `MetricsGroup`
type SourceId int32

const (
	SourceId_SOURCE_ID_UNSPECIFIED  SourceId = 0
	SourceId_SOURCE_ETHTOOL         SourceId = 1
	SourceId_SOURCE_IP_S_LINK       SourceId = 2
	SourceId_SOURCE_NSTAT           SourceId = 3
	SourceId_SOURCE_SNMP            SourceId = 4
	SourceId_SOURCE_PROC_INTERRUPTS SourceId = 5
	SourceId_SOURCE_AGENT_EVENT     SourceId = 6
)

// Enum value maps for SourceId.
var (
	SourceId_name = map[int32]string{
		0: "SOURCE_ID_UNSPECIFIED",
		1: "SOURCE_ETHTOOL",
		2: "SOURCE_IP_S_LINK",
		3: "SOURCE_NSTAT",
		4: "SOURCE_SNMP",
		5: "SOURCE_PROC_INTERRUPTS",
		6: "SOURCE_AGENT_EVENT",
	}
	SourceId_value = map[string]int32{
		"SOURCE_ID_UNSPECIFIED":  0,
		"SOURCE_ETHTOOL":         1,
		"SOURCE_IP_S_LINK":       2,
		"SOURCE_NSTAT":           3,
		"SOURCE_SNMP":            4,
		"SOURCE_PROC_INTERRUPTS": 5,
		"SOURCE_AGENT_EVENT":     6,
	}
)

func (x SourceId) Enum() *SourceId {
	p := new(SourceId)
	*p = x
	return p
}

func (x SourceId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceId) Descriptor() protoreflect.EnumDescriptor {
	return file_network_stats_report_proto_enumTypes[1].Descriptor()
}

func (SourceId) Type() protoreflect.EnumType {
	return &file_network_stats_report_proto_enumTypes[1]
}

func (x SourceId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Provides mappings for `device_element_identifier_type` in
// `MetricsGroupIdentifiers`
type DeviceElementType int32

const (
	DeviceElementType_ELEMENT_UNSPECIFIED    DeviceElementType = 0
	DeviceElementType_ELEMENT_MAC_ADDRESS    DeviceElementType = 1
	DeviceElementType_ELEMENT_BUS_ADDRESS    DeviceElementType = 2
	DeviceElementType_ELEMENT_INTERFACE_NAME DeviceElementType = 3
	DeviceElementType_ELEMENT_DRIVER_NAME    DeviceElementType = 4
)

// Enum value maps for DeviceElementType.
var (
	DeviceElementType_name = map[int32]string{
		0: "ELEMENT_UNSPECIFIED",
		1: "ELEMENT_MAC_ADDRESS",
		2: "ELEMENT_BUS_ADDRESS",
		3: "ELEMENT_INTERFACE_NAME",
		4: "ELEMENT_DRIVER_NAME",
	}
	DeviceElementType_value = map[string]int32{
		"ELEMENT_UNSPECIFIED":    0,
		"ELEMENT_MAC_ADDRESS":    1,
		"ELEMENT_BUS_ADDRESS":    2,
		"ELEMENT_INTERFACE_NAME": 3,
		"ELEMENT_DRIVER_NAME":    4,
	}
)

func (x DeviceElementType) Enum() *DeviceElementType {
	p := new(DeviceElementType)
	*p = x
	return p
}

func (x DeviceElementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceElementType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_stats_report_proto_enumTypes[2].Descriptor()
}

func (DeviceElementType) Type() protoreflect.EnumType {
	return &file_network_stats_report_proto_enumTypes[2]
}

func (x DeviceElementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Identifier that can be added to MetricsGroup to denote additional system
// information
type MetricsGroupIdentifier struct {
	state                                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeviceElementIdentifierType DeviceElementType      `protobuf:"varint,1,opt,name=device_element_identifier_type,json=deviceElementIdentifierType,enum=cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.DeviceElementType"`
	xxx_hidden_DeviceElementIdentifier     *string                `protobuf:"bytes,2,opt,name=device_element_identifier,json=deviceElementIdentifier"`
	XXX_raceDetectHookData                 protoimpl.RaceDetectHookData
	XXX_presence                           [1]uint32
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *MetricsGroupIdentifier) Reset() {
	*x = MetricsGroupIdentifier{}
	mi := &file_network_stats_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsGroupIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsGroupIdentifier) ProtoMessage() {}

func (x *MetricsGroupIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_network_stats_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetricsGroupIdentifier) GetDeviceElementIdentifierType() DeviceElementType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_DeviceElementIdentifierType
		}
	}
	return DeviceElementType_ELEMENT_UNSPECIFIED
}

func (x *MetricsGroupIdentifier) GetDeviceElementIdentifier() string {
	if x != nil {
		if x.xxx_hidden_DeviceElementIdentifier != nil {
			return *x.xxx_hidden_DeviceElementIdentifier
		}
		return ""
	}
	return ""
}

func (x *MetricsGroupIdentifier) SetDeviceElementIdentifierType(v DeviceElementType) {
	x.xxx_hidden_DeviceElementIdentifierType = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *MetricsGroupIdentifier) SetDeviceElementIdentifier(v string) {
	x.xxx_hidden_DeviceElementIdentifier = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *MetricsGroupIdentifier) HasDeviceElementIdentifierType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MetricsGroupIdentifier) HasDeviceElementIdentifier() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MetricsGroupIdentifier) ClearDeviceElementIdentifierType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DeviceElementIdentifierType = DeviceElementType_ELEMENT_UNSPECIFIED
}

func (x *MetricsGroupIdentifier) ClearDeviceElementIdentifier() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DeviceElementIdentifier = nil
}

type MetricsGroupIdentifier_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Refer to `DeviceElementType` enum for identifier mappings
	DeviceElementIdentifierType *DeviceElementType
	// Device identifier (i.e. bus address/MAC address)
	DeviceElementIdentifier *string
}

func (b0 MetricsGroupIdentifier_builder) Build() *MetricsGroupIdentifier {
	m0 := &MetricsGroupIdentifier{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DeviceElementIdentifierType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_DeviceElementIdentifierType = *b.DeviceElementIdentifierType
	}
	if b.DeviceElementIdentifier != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_DeviceElementIdentifier = b.DeviceElementIdentifier
	}
	return m0
}

// The representation for a single metric - that value can be any one
// of the provided data types
type MetricValue struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value isMetricValue_Value    `protobuf_oneof:"value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricValue) Reset() {
	*x = MetricValue{}
	mi := &file_network_stats_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricValue) ProtoMessage() {}

func (x *MetricValue) ProtoReflect() protoreflect.Message {
	mi := &file_network_stats_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetricValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*metricValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetricValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*metricValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *MetricValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*metricValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MetricValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Value.(*metricValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *MetricValue) SetIntValue(v int64) {
	x.xxx_hidden_Value = &metricValue_IntValue{v}
}

func (x *MetricValue) SetDoubleValue(v float64) {
	x.xxx_hidden_Value = &metricValue_DoubleValue{v}
}

func (x *MetricValue) SetStringValue(v string) {
	x.xxx_hidden_Value = &metricValue_StringValue{v}
}

func (x *MetricValue) SetBoolValue(v bool) {
	x.xxx_hidden_Value = &metricValue_BoolValue{v}
}

func (x *MetricValue) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *MetricValue) HasIntValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*metricValue_IntValue)
	return ok
}

func (x *MetricValue) HasDoubleValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*metricValue_DoubleValue)
	return ok
}

func (x *MetricValue) HasStringValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*metricValue_StringValue)
	return ok
}

func (x *MetricValue) HasBoolValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Value.(*metricValue_BoolValue)
	return ok
}

func (x *MetricValue) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *MetricValue) ClearIntValue() {
	if _, ok := x.xxx_hidden_Value.(*metricValue_IntValue); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *MetricValue) ClearDoubleValue() {
	if _, ok := x.xxx_hidden_Value.(*metricValue_DoubleValue); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *MetricValue) ClearStringValue() {
	if _, ok := x.xxx_hidden_Value.(*metricValue_StringValue); ok {
		x.xxx_hidden_Value = nil
	}
}

func (x *MetricValue) ClearBoolValue() {
	if _, ok := x.xxx_hidden_Value.(*metricValue_BoolValue); ok {
		x.xxx_hidden_Value = nil
	}
}

const MetricValue_Value_not_set_case case_MetricValue_Value = 0
const MetricValue_IntValue_case case_MetricValue_Value = 1
const MetricValue_DoubleValue_case case_MetricValue_Value = 2
const MetricValue_StringValue_case case_MetricValue_Value = 3
const MetricValue_BoolValue_case case_MetricValue_Value = 4

func (x *MetricValue) WhichValue() case_MetricValue_Value {
	if x == nil {
		return MetricValue_Value_not_set_case
	}
	switch x.xxx_hidden_Value.(type) {
	case *metricValue_IntValue:
		return MetricValue_IntValue_case
	case *metricValue_DoubleValue:
		return MetricValue_DoubleValue_case
	case *metricValue_StringValue:
		return MetricValue_StringValue_case
	case *metricValue_BoolValue:
		return MetricValue_BoolValue_case
	default:
		return MetricValue_Value_not_set_case
	}
}

type MetricValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Value:
	IntValue    *int64
	DoubleValue *float64
	StringValue *string
	BoolValue   *bool
	// -- end of xxx_hidden_Value
}

func (b0 MetricValue_builder) Build() *MetricValue {
	m0 := &MetricValue{}
	b, x := &b0, m0
	_, _ = b, x
	if b.IntValue != nil {
		x.xxx_hidden_Value = &metricValue_IntValue{*b.IntValue}
	}
	if b.DoubleValue != nil {
		x.xxx_hidden_Value = &metricValue_DoubleValue{*b.DoubleValue}
	}
	if b.StringValue != nil {
		x.xxx_hidden_Value = &metricValue_StringValue{*b.StringValue}
	}
	if b.BoolValue != nil {
		x.xxx_hidden_Value = &metricValue_BoolValue{*b.BoolValue}
	}
	return m0
}

type case_MetricValue_Value protoreflect.FieldNumber

func (x case_MetricValue_Value) String() string {
	md := file_network_stats_report_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isMetricValue_Value interface {
	isMetricValue_Value()
}

type metricValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,oneof"`
}

type metricValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,oneof"`
}

type metricValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,oneof"`
}

type metricValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,oneof"`
}

func (*metricValue_IntValue) isMetricValue_Value() {}

func (*metricValue_DoubleValue) isMetricValue_Value() {}

func (*metricValue_StringValue) isMetricValue_Value() {}

func (*metricValue_BoolValue) isMetricValue_Value() {}

// Contains all statistics collected from a single tool/command execution.
type MetricsGroup struct {
	state                              protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Source                  uint64                     `protobuf:"varint,1,opt,name=source"`
	xxx_hidden_MetricsGroupIdentifiers *[]*MetricsGroupIdentifier `protobuf:"bytes,2,rep,name=metrics_group_identifiers,json=metricsGroupIdentifiers"`
	xxx_hidden_Metrics                 map[uint64]*MetricValue    `protobuf:"bytes,3,rep,name=metrics" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_StartTimestamp          *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=start_timestamp,json=startTimestamp"`
	xxx_hidden_EndTimestamp            *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=end_timestamp,json=endTimestamp"`
	xxx_hidden_AgentMetrics            map[string]*MetricValue    `protobuf:"bytes,6,rep,name=agent_metrics,json=agentMetrics" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData             protoimpl.RaceDetectHookData
	XXX_presence                       [1]uint32
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *MetricsGroup) Reset() {
	*x = MetricsGroup{}
	mi := &file_network_stats_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsGroup) ProtoMessage() {}

func (x *MetricsGroup) ProtoReflect() protoreflect.Message {
	mi := &file_network_stats_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetricsGroup) GetSource() uint64 {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return 0
}

func (x *MetricsGroup) GetMetricsGroupIdentifiers() []*MetricsGroupIdentifier {
	if x != nil {
		if x.xxx_hidden_MetricsGroupIdentifiers != nil {
			return *x.xxx_hidden_MetricsGroupIdentifiers
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in network_stats_report.proto.
func (x *MetricsGroup) GetMetrics() map[uint64]*MetricValue {
	if x != nil {
		return x.xxx_hidden_Metrics
	}
	return nil
}

func (x *MetricsGroup) GetStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartTimestamp
	}
	return nil
}

func (x *MetricsGroup) GetEndTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndTimestamp
	}
	return nil
}

func (x *MetricsGroup) GetAgentMetrics() map[string]*MetricValue {
	if x != nil {
		return x.xxx_hidden_AgentMetrics
	}
	return nil
}

func (x *MetricsGroup) SetSource(v uint64) {
	x.xxx_hidden_Source = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *MetricsGroup) SetMetricsGroupIdentifiers(v []*MetricsGroupIdentifier) {
	x.xxx_hidden_MetricsGroupIdentifiers = &v
}

// Deprecated: Marked as deprecated in network_stats_report.proto.
func (x *MetricsGroup) SetMetrics(v map[uint64]*MetricValue) {
	x.xxx_hidden_Metrics = v
}

func (x *MetricsGroup) SetStartTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartTimestamp = v
}

func (x *MetricsGroup) SetEndTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndTimestamp = v
}

func (x *MetricsGroup) SetAgentMetrics(v map[string]*MetricValue) {
	x.xxx_hidden_AgentMetrics = v
}

func (x *MetricsGroup) HasSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MetricsGroup) HasStartTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartTimestamp != nil
}

func (x *MetricsGroup) HasEndTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndTimestamp != nil
}

func (x *MetricsGroup) ClearSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Source = 0
}

func (x *MetricsGroup) ClearStartTimestamp() {
	x.xxx_hidden_StartTimestamp = nil
}

func (x *MetricsGroup) ClearEndTimestamp() {
	x.xxx_hidden_EndTimestamp = nil
}

type MetricsGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Refer to `SourceId` enum for identifier mappings
	Source *uint64
	// A set of identifiers used for additional system descriptions/tags where
	// these metrics were collected. This field is empty or not set if the metrics
	// are system-wide.
	MetricsGroupIdentifiers []*MetricsGroupIdentifier
	// Refer to `MetricId` enum for identifier mappings
	//
	// Deprecated: Marked as deprecated in network_stats_report.proto.
	Metrics map[uint64]*MetricValue
	// Timestamp when collecting metrics for this group was started.
	StartTimestamp *timestamppb.Timestamp
	// Timestamp when collecting metrics for this group was ended.
	EndTimestamp *timestamppb.Timestamp
	// Key-value pairs of metrics collected from the source.
	AgentMetrics map[string]*MetricValue
}

func (b0 MetricsGroup_builder) Build() *MetricsGroup {
	m0 := &MetricsGroup{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Source != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Source = *b.Source
	}
	x.xxx_hidden_MetricsGroupIdentifiers = &b.MetricsGroupIdentifiers
	x.xxx_hidden_Metrics = b.Metrics
	x.xxx_hidden_StartTimestamp = b.StartTimestamp
	x.xxx_hidden_EndTimestamp = b.EndTimestamp
	x.xxx_hidden_AgentMetrics = b.AgentMetrics
	return m0
}

// Represents a single report of network statistics for a specific instance.
type NetworkStatsReport struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metrics                  *[]*MetricsGroup       `protobuf:"bytes,1,rep,name=metrics"`
	xxx_hidden_CollectionStartTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=collection_start_timestamp,json=collectionStartTimestamp"`
	xxx_hidden_CollectionEndTimestamp   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collection_end_timestamp,json=collectionEndTimestamp"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *NetworkStatsReport) Reset() {
	*x = NetworkStatsReport{}
	mi := &file_network_stats_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatsReport) ProtoMessage() {}

func (x *NetworkStatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_network_stats_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkStatsReport) GetMetrics() []*MetricsGroup {
	if x != nil {
		if x.xxx_hidden_Metrics != nil {
			return *x.xxx_hidden_Metrics
		}
	}
	return nil
}

func (x *NetworkStatsReport) GetCollectionStartTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CollectionStartTimestamp
	}
	return nil
}

func (x *NetworkStatsReport) GetCollectionEndTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CollectionEndTimestamp
	}
	return nil
}

func (x *NetworkStatsReport) SetMetrics(v []*MetricsGroup) {
	x.xxx_hidden_Metrics = &v
}

func (x *NetworkStatsReport) SetCollectionStartTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_CollectionStartTimestamp = v
}

func (x *NetworkStatsReport) SetCollectionEndTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_CollectionEndTimestamp = v
}

func (x *NetworkStatsReport) HasCollectionStartTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CollectionStartTimestamp != nil
}

func (x *NetworkStatsReport) HasCollectionEndTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CollectionEndTimestamp != nil
}

func (x *NetworkStatsReport) ClearCollectionStartTimestamp() {
	x.xxx_hidden_CollectionStartTimestamp = nil
}

func (x *NetworkStatsReport) ClearCollectionEndTimestamp() {
	x.xxx_hidden_CollectionEndTimestamp = nil
}

type NetworkStatsReport_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A collection of stats, with each element containing all stats
	// gathered from a specific tool or source.
	Metrics []*MetricsGroup
	// Timestamp when metrics collection started.
	CollectionStartTimestamp *timestamppb.Timestamp
	// Timestamp when metrics collection ended.
	CollectionEndTimestamp *timestamppb.Timestamp
}

func (b0 NetworkStatsReport_builder) Build() *NetworkStatsReport {
	m0 := &NetworkStatsReport{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metrics = &b.Metrics
	x.xxx_hidden_CollectionStartTimestamp = b.CollectionStartTimestamp
	x.xxx_hidden_CollectionEndTimestamp = b.CollectionEndTimestamp
	return m0
}

var File_network_stats_report_proto protoreflect.FileDescriptor

const file_network_stats_report_proto_rawDesc = "" +
	"\n" +
	"\x1anetwork_stats_report.proto\x128cloud_cluster_guest_net_drivers_guest_agent_plugin_proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x01\n" +
	"\x16MetricsGroupIdentifier\x12\x90\x01\n" +
	"\x1edevice_element_identifier_type\x18\x01 \x01(\x0e2K.cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.DeviceElementTypeR\x1bdeviceElementIdentifierType\x12:\n" +
	"\x19device_element_identifier\x18\x02 \x01(\tR\x17deviceElementIdentifier\"\xa0\x01\n" +
	"\vMetricValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"\xba\x06\n" +
	"\fMetricsGroup\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x04R\x06source\x12\x8c\x01\n" +
	"\x19metrics_group_identifiers\x18\x02 \x03(\v2P.cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroupIdentifierR\x17metricsGroupIdentifiers\x12q\n" +
	"\ametrics\x18\x03 \x03(\v2S.cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.MetricsEntryB\x02\x18\x01R\ametrics\x12C\n" +
	"\x0fstart_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0estartTimestamp\x12?\n" +
	"\rend_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fendTimestamp\x12}\n" +
	"\ragent_metrics\x18\x06 \x03(\v2X.cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.AgentMetricsEntryR\fagentMetrics\x1a\x81\x01\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12[\n" +
	"\x05value\x18\x02 \x01(\v2E.cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricValueR\x05value:\x028\x01\x1a\x86\x01\n" +
	"\x11AgentMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12[\n" +
	"\x05value\x18\x02 \x01(\v2E.cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricValueR\x05value:\x028\x01\"\xa6\x02\n" +
	"\x12NetworkStatsReport\x12`\n" +
	"\ametrics\x18\x01 \x03(\v2F.cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroupR\ametrics\x12X\n" +
	"\x1acollection_start_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x18collectionStartTimestamp\x12T\n" +
	"\x18collection_end_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x16collectionEndTimestamp*\xc3\x01\n" +
	"\bMetricId\x12\x19\n" +
	"\x15METRIC_ID_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"RX_PACKETS\x10\x01\x12\x0e\n" +
	"\n" +
	"TX_PACKETS\x10\x02\x12\f\n" +
	"\bRX_BYTES\x10\x03\x12\f\n" +
	"\bTX_BYTES\x10\x04\x12\x11\n" +
	"\rLINK_DETECTED\x10\x05\x12\x12\n" +
	"\x0eDRIVER_VERSION\x10\x06\x12\x12\n" +
	"\x0ePACKET_DROPPED\x10\a\x12\x11\n" +
	"\rAGENT_STARTED\x10\b\x12\x12\n" +
	"\x0eKERNEL_VERSION\x10\t*\xa6\x01\n" +
	"\bSourceId\x12\x19\n" +
	"\x15SOURCE_ID_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSOURCE_ETHTOOL\x10\x01\x12\x14\n" +
	"\x10SOURCE_IP_S_LINK\x10\x02\x12\x10\n" +
	"\fSOURCE_NSTAT\x10\x03\x12\x0f\n" +
	"\vSOURCE_SNMP\x10\x04\x12\x1a\n" +
	"\x16SOURCE_PROC_INTERRUPTS\x10\x05\x12\x16\n" +
	"\x12SOURCE_AGENT_EVENT\x10\x06*\x93\x01\n" +
	"\x11DeviceElementType\x12\x17\n" +
	"\x13ELEMENT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ELEMENT_MAC_ADDRESS\x10\x01\x12\x17\n" +
	"\x13ELEMENT_BUS_ADDRESS\x10\x02\x12\x1a\n" +
	"\x16ELEMENT_INTERFACE_NAME\x10\x03\x12\x17\n" +
	"\x13ELEMENT_DRIVER_NAME\x10\x04B\x17Z\x15/network_stats_reportb\beditionsp\xe9\a"

var file_network_stats_report_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_network_stats_report_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_network_stats_report_proto_goTypes = []any{
	(MetricId)(0),                  // 0: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricId
	(SourceId)(0),                  // 1: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.SourceId
	(DeviceElementType)(0),         // 2: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.DeviceElementType
	(*MetricsGroupIdentifier)(nil), // 3: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroupIdentifier
	(*MetricValue)(nil),            // 4: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricValue
	(*MetricsGroup)(nil),           // 5: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup
	(*NetworkStatsReport)(nil),     // 6: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.NetworkStatsReport
	nil,                            // 7: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.MetricsEntry
	nil,                            // 8: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.AgentMetricsEntry
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_network_stats_report_proto_depIdxs = []int32{
	2,  // 0: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroupIdentifier.device_element_identifier_type:type_name -> cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.DeviceElementType
	3,  // 1: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.metrics_group_identifiers:type_name -> cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroupIdentifier
	7,  // 2: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.metrics:type_name -> cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.MetricsEntry
	9,  // 3: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.start_timestamp:type_name -> google.protobuf.Timestamp
	9,  // 4: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.end_timestamp:type_name -> google.protobuf.Timestamp
	8,  // 5: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.agent_metrics:type_name -> cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.AgentMetricsEntry
	5,  // 6: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.NetworkStatsReport.metrics:type_name -> cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup
	9,  // 7: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.NetworkStatsReport.collection_start_timestamp:type_name -> google.protobuf.Timestamp
	9,  // 8: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.NetworkStatsReport.collection_end_timestamp:type_name -> google.protobuf.Timestamp
	4,  // 9: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.MetricsEntry.value:type_name -> cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricValue
	4,  // 10: cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricsGroup.AgentMetricsEntry.value:type_name -> cloud_cluster_guest_net_drivers_guest_agent_plugin_proto.MetricValue
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_network_stats_report_proto_init() }
func file_network_stats_report_proto_init() {
	if File_network_stats_report_proto != nil {
		return
	}
	file_network_stats_report_proto_msgTypes[1].OneofWrappers = []any{
		(*metricValue_IntValue)(nil),
		(*metricValue_DoubleValue)(nil),
		(*metricValue_StringValue)(nil),
		(*metricValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_stats_report_proto_rawDesc), len(file_network_stats_report_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_stats_report_proto_goTypes,
		DependencyIndexes: file_network_stats_report_proto_depIdxs,
		EnumInfos:         file_network_stats_report_proto_enumTypes,
		MessageInfos:      file_network_stats_report_proto_msgTypes,
	}.Build()
	File_network_stats_report_proto = out.File
	file_network_stats_report_proto_goTypes = nil
	file_network_stats_report_proto_depIdxs = nil
}
