# proto-file: isvdiscovery/proto/definition.proto
# proto-message: DiscoveryRules

rules: {
  discovered_workload_name: "apachewebserver"
  any: {
    conditions: [
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "httpd"
        }
      },
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "apache2"
        }
      }
    ]
  }
  version_rules: [
    {
      command: USE_DISCOVERED_PROCESS_PATH
      command_args: ["-v"]
      regex_match: "^Server version: Apache\\/(\\d+(?:\\.\\d+)+)"
    },
    {
      command: HTTPD
      command_args: ["-v"]
      regex_match: "^Server version: Apache\\/(\\d+(?:\\.\\d+)+)"
    },
    {
      command: APACHE2
      command_args: ["-v"]
      regex_match: "^Server version: Apache\\/(\\d+(?:\\.\\d+)+)"
    }
  ]
}
