# proto-file: isvdiscovery/proto/definition.proto
# proto-message: DiscoveryRules

rules: {
  discovered_workload_name: "oracledataguard"
  any: {
    conditions: [
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "ora_mrp"
        }
      },
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "ora_rfs"
        }
      },
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "ora_dmon"
        }
      },
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "ora_lsp"
        }
      }
    ]
  }
  version_rules: [
    {
      command: DGMGRL
      command_args: ["-v"]
      # TODO: b/479503774 - Update the regex once example output is available.
      regex_match: "[Vv]ersion"
    }
  ]
}
