# proto-file: isvdiscovery/proto/definition.proto
# proto-message: DiscoveryRules

rules: {
  discovered_workload_name: "susepacemaker"
  any: {
    conditions: [
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "pacemakerd"
        }
      },
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "pacemaker_remoted"
        }
      }
    ]
  }
  version_rules: [
    {
      command: PACEMAKERD
      command_args: ["--version"]
      regex_match: "^Pacemaker\\s+([0-9]+\\.[0-9]+\\.[0-9]+(?:-[a-zA-Z0-9._]+)?)$"
    }
  ]
}
