# proto-file: isvdiscovery/proto/definition.proto
# proto-message: DiscoveryRules

rules: {
  discovered_workload_name: "postgresql"
  condition: {
    string_match: {
      vm_field: VM_PROCESS_NAME
      regex_match: "postgres"
    }
  }
  version_rules: [
    {
      command: POSTGRES
      command_args: ["--version"]
      regex_match: "(?i)postgre(sql|s).* \\d+(\\.\\d+)*"
    },
    {
      command: PSQL
      command_args: ["--version"]
      regex_match: "(?i)postgre(sql|s).* \\d+(\\.\\d+)*"
    }
  ]
}
