# proto-file: isvdiscovery/proto/definition.proto
# proto-message: DiscoveryRules

rules: {
  discovered_workload_name: "sapgateway"
  any: {
    conditions: [
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "gwrd"
        }
      },
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "gwrd.exe"
        }
      }
    ]
  }
  version_rules: [
    {
      command: GWRD
      command_args: ["-v"]
      regex_match: "kernel release\\s+(?<release>\\d+)(?:.|\\n)*?patch number\\s+(?<patch>\\d+)"
    }
  ]
}
