# proto-file: isvdiscovery/proto/definition.proto
# proto-message: DiscoveryRules

rules: {
  discovered_workload_name: "sapiq"
  condition: {
    string_match: {
      vm_field: VM_PROCESS_NAME
      regex_match: "iqsrv"
    }
  }
  version_rules: [
    {
      command: IQ15
      command_args: ["-v"]
      regex_match: "^(Sybase|SAP)\\sIQ\\/(\\d+\\.\\d+\\.\\d+\\.\\d+)"
    },
    {
      command: IQ16
      command_args: ["-v"]
      regex_match: "^(Sybase|SAP)\\sIQ\\/(\\d+\\.\\d+\\.\\d+\\.\\d+)"
    },
    {
      command: IQ15WINDOWS
      command_args: ["-v"]
      regex_match: "^(Sybase|SAP)\\sIQ\\/(\\d+\\.\\d+\\.\\d+\\.\\d+)"
    },
    {
      command: IQ16WINDOWS
      command_args: ["-v"]
      regex_match: "^(Sybase|SAP)\\sIQ\\/(\\d+\\.\\d+\\.\\d+\\.\\d+)"
    }
  ]
}
