# proto-file: isvdiscovery/proto/definition.proto
# proto-message: DiscoveryRules

rules: {
  discovered_workload_name: "weblogicserver"
  all: {
    conditions: [
      {
        string_match: {
          vm_field: VM_PROCESS_NAME
          regex_match: "java"
        }
      }
    ]
    any: {
      conditions: [
        {
          string_match: {
            vm_field: VM_CLI_ARGS
            regex_match: "Dweblogic.Name"
          }
        },
        {
          string_match: {
            vm_field: VM_CLI_ARGS
            regex_match: "weblogic.Server"
          }
        },
        {
          string_match: {
            vm_field: VM_ENV_VARS
            regex_match: "WL_HOME"
          }
        },
        {
          string_match: {
            vm_field: VM_ENV_VARS
            regex_match: "MW_HOME"
          }
        }
      ]
    }
  }
  version_rules: [
    {
      command: JAVA
      command_args: ["-cp $WL_HOME/server/lib/weblogic.jar weblogic.version"]
      # TODO: b/479503774 - Update the regex once example output is available.
      regex_match: "[Vv]ersion"
    }
  ]
}
