//  Copyright 2019 Google
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: snapshot_service.proto

package cloud_vmm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_NOT_SET       OperationType = 0
	OperationType_PRE_SNAPSHOT  OperationType = 1
	OperationType_POST_SNAPSHOT OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "NOT_SET",
		1: "PRE_SNAPSHOT",
		2: "POST_SNAPSHOT",
	}
	OperationType_value = map[string]int32{
		"NOT_SET":       0,
		"PRE_SNAPSHOT":  1,
		"POST_SNAPSHOT": 2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_service_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_snapshot_service_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{0}
}

type SupportedFeatures int32

const (
	SupportedFeatures_NONE      SupportedFeatures = 0
	SupportedFeatures_SNAPSHOTS SupportedFeatures = 1
)

// Enum value maps for SupportedFeatures.
var (
	SupportedFeatures_name = map[int32]string{
		0: "NONE",
		1: "SNAPSHOTS",
	}
	SupportedFeatures_value = map[string]int32{
		"NONE":      0,
		"SNAPSHOTS": 1,
	}
)

func (x SupportedFeatures) Enum() *SupportedFeatures {
	p := new(SupportedFeatures)
	*p = x
	return p
}

func (x SupportedFeatures) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SupportedFeatures) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_service_proto_enumTypes[1].Descriptor()
}

func (SupportedFeatures) Type() protoreflect.EnumType {
	return &file_snapshot_service_proto_enumTypes[1]
}

func (x SupportedFeatures) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SupportedFeatures.Descriptor instead.
func (SupportedFeatures) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{1}
}

type AgentErrorCode int32

const (
	AgentErrorCode_NO_ERROR AgentErrorCode = 0
	// The snapshot config was improper in some way.
	AgentErrorCode_INVALID_CONFIG AgentErrorCode = 1
	// The pre or post snapshot script was not found on disk.
	AgentErrorCode_SCRIPT_NOT_FOUND AgentErrorCode = 2
	// The pre or post snapshot script timed out.
	AgentErrorCode_SCRIPT_TIMED_OUT AgentErrorCode = 3
	// The pre or post snapshot script returned an error, but the "continue on
	// error" flag was not set.
	AgentErrorCode_UNHANDLED_SCRIPT_ERROR AgentErrorCode = 4
)

// Enum value maps for AgentErrorCode.
var (
	AgentErrorCode_name = map[int32]string{
		0: "NO_ERROR",
		1: "INVALID_CONFIG",
		2: "SCRIPT_NOT_FOUND",
		3: "SCRIPT_TIMED_OUT",
		4: "UNHANDLED_SCRIPT_ERROR",
	}
	AgentErrorCode_value = map[string]int32{
		"NO_ERROR":               0,
		"INVALID_CONFIG":         1,
		"SCRIPT_NOT_FOUND":       2,
		"SCRIPT_TIMED_OUT":       3,
		"UNHANDLED_SCRIPT_ERROR": 4,
	}
)

func (x AgentErrorCode) Enum() *AgentErrorCode {
	p := new(AgentErrorCode)
	*p = x
	return p
}

func (x AgentErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_service_proto_enumTypes[2].Descriptor()
}

func (AgentErrorCode) Type() protoreflect.EnumType {
	return &file_snapshot_service_proto_enumTypes[2]
}

func (x AgentErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentErrorCode.Descriptor instead.
func (AgentErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{2}
}

type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operation id of the snapshot.
	OperationId int32 `protobuf:"varint,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// A list of comma separated target/lun values, e.g. "1/2,3/4".
	DiskList string `protobuf:"bytes,2,opt,name=disk_list,json=diskList,proto3" json:"disk_list,omitempty"`
	// The operation type.
	Type OperationType `protobuf:"varint,3,opt,name=type,proto3,enum=cloud.vmm.OperationType" json:"type,omitempty"`
	// A list of comma separated NGUIDs for NVMe disks. If a NVMe disk does not
	// have an NGUID, an empty string will be used.
	NguidList     string `protobuf:"bytes,4,opt,name=nguid_list,json=nguidList,proto3" json:"nguid_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_snapshot_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRequest) GetOperationId() int32 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *SnapshotRequest) GetDiskList() string {
	if x != nil {
		return x.DiskList
	}
	return ""
}

func (x *SnapshotRequest) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_NOT_SET
}

func (x *SnapshotRequest) GetNguidList() string {
	if x != nil {
		return x.NguidList
	}
	return ""
}

type ServerInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SupportedFeatures []SupportedFeatures    `protobuf:"varint,1,rep,packed,name=supported_features,json=supportedFeatures,proto3,enum=cloud.vmm.SupportedFeatures" json:"supported_features,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_snapshot_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetSupportedFeatures() []SupportedFeatures {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

type SnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operation id of the snapshot.
	OperationId int32 `protobuf:"varint,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// The return code of the scripts run by the guest. If this is non-zero, then
	// agent_return_code should be UNHANDLED_SCRIPT_ERROR.
	ScriptsReturnCode int32 `protobuf:"varint,2,opt,name=scripts_return_code,json=scriptsReturnCode,proto3" json:"scripts_return_code,omitempty"`
	// The agent return code.
	AgentReturnCode AgentErrorCode `protobuf:"varint,3,opt,name=agent_return_code,json=agentReturnCode,proto3,enum=cloud.vmm.AgentErrorCode" json:"agent_return_code,omitempty"`
	// The operation type.
	Type          OperationType `protobuf:"varint,4,opt,name=type,proto3,enum=cloud.vmm.OperationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_snapshot_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotResponse) GetOperationId() int32 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *SnapshotResponse) GetScriptsReturnCode() int32 {
	if x != nil {
		return x.ScriptsReturnCode
	}
	return 0
}

func (x *SnapshotResponse) GetAgentReturnCode() AgentErrorCode {
	if x != nil {
		return x.AgentReturnCode
	}
	return AgentErrorCode_NO_ERROR
}

func (x *SnapshotResponse) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_NOT_SET
}

type GuestReady struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestServerInfo bool                   `protobuf:"varint,1,opt,name=request_server_info,json=requestServerInfo,proto3" json:"request_server_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GuestReady) Reset() {
	*x = GuestReady{}
	mi := &file_snapshot_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestReady) ProtoMessage() {}

func (x *GuestReady) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestReady.ProtoReflect.Descriptor instead.
func (*GuestReady) Descriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{3}
}

func (x *GuestReady) GetRequestServerInfo() bool {
	if x != nil {
		return x.RequestServerInfo
	}
	return false
}

type GuestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GuestMessage_SnapshotRequest
	//	*GuestMessage_ServerInfo
	Msg           isGuestMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestMessage) Reset() {
	*x = GuestMessage{}
	mi := &file_snapshot_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestMessage) ProtoMessage() {}

func (x *GuestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestMessage.ProtoReflect.Descriptor instead.
func (*GuestMessage) Descriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{4}
}

func (x *GuestMessage) GetMsg() isGuestMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GuestMessage) GetSnapshotRequest() *SnapshotRequest {
	if x != nil {
		if x, ok := x.Msg.(*GuestMessage_SnapshotRequest); ok {
			return x.SnapshotRequest
		}
	}
	return nil
}

func (x *GuestMessage) GetServerInfo() *ServerInfo {
	if x != nil {
		if x, ok := x.Msg.(*GuestMessage_ServerInfo); ok {
			return x.ServerInfo
		}
	}
	return nil
}

type isGuestMessage_Msg interface {
	isGuestMessage_Msg()
}

type GuestMessage_SnapshotRequest struct {
	SnapshotRequest *SnapshotRequest `protobuf:"bytes,1,opt,name=snapshot_request,json=snapshotRequest,proto3,oneof"`
}

type GuestMessage_ServerInfo struct {
	ServerInfo *ServerInfo `protobuf:"bytes,2,opt,name=server_info,json=serverInfo,proto3,oneof"`
}

func (*GuestMessage_SnapshotRequest) isGuestMessage_Msg() {}

func (*GuestMessage_ServerInfo) isGuestMessage_Msg() {}

type ServerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAck) Reset() {
	*x = ServerAck{}
	mi := &file_snapshot_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAck) ProtoMessage() {}

func (x *ServerAck) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAck.ProtoReflect.Descriptor instead.
func (*ServerAck) Descriptor() ([]byte, []int) {
	return file_snapshot_service_proto_rawDescGZIP(), []int{5}
}

var File_snapshot_service_proto protoreflect.FileDescriptor

const file_snapshot_service_proto_rawDesc = "" +
	"\n" +
	"\x16snapshot_service.proto\x12\tcloud.vmm\"\x9e\x01\n" +
	"\x0fSnapshotRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\x05R\voperationId\x12\x1b\n" +
	"\tdisk_list\x18\x02 \x01(\tR\bdiskList\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.cloud.vmm.OperationTypeR\x04type\x12\x1d\n" +
	"\n" +
	"nguid_list\x18\x04 \x01(\tR\tnguidList\"Y\n" +
	"\n" +
	"ServerInfo\x12K\n" +
	"\x12supported_features\x18\x01 \x03(\x0e2\x1c.cloud.vmm.SupportedFeaturesR\x11supportedFeatures\"\xda\x01\n" +
	"\x10SnapshotResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\x05R\voperationId\x12.\n" +
	"\x13scripts_return_code\x18\x02 \x01(\x05R\x11scriptsReturnCode\x12E\n" +
	"\x11agent_return_code\x18\x03 \x01(\x0e2\x19.cloud.vmm.AgentErrorCodeR\x0fagentReturnCode\x12,\n" +
	"\x04type\x18\x04 \x01(\x0e2\x18.cloud.vmm.OperationTypeR\x04type\"<\n" +
	"\n" +
	"GuestReady\x12.\n" +
	"\x13request_server_info\x18\x01 \x01(\bR\x11requestServerInfo\"\x98\x01\n" +
	"\fGuestMessage\x12G\n" +
	"\x10snapshot_request\x18\x01 \x01(\v2\x1a.cloud.vmm.SnapshotRequestH\x00R\x0fsnapshotRequest\x128\n" +
	"\vserver_info\x18\x02 \x01(\v2\x15.cloud.vmm.ServerInfoH\x00R\n" +
	"serverInfoB\x05\n" +
	"\x03msg\"\v\n" +
	"\tServerAck*A\n" +
	"\rOperationType\x12\v\n" +
	"\aNOT_SET\x10\x00\x12\x10\n" +
	"\fPRE_SNAPSHOT\x10\x01\x12\x11\n" +
	"\rPOST_SNAPSHOT\x10\x02*,\n" +
	"\x11SupportedFeatures\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tSNAPSHOTS\x10\x01*z\n" +
	"\x0eAgentErrorCode\x12\f\n" +
	"\bNO_ERROR\x10\x00\x12\x12\n" +
	"\x0eINVALID_CONFIG\x10\x01\x12\x14\n" +
	"\x10SCRIPT_NOT_FOUND\x10\x02\x12\x14\n" +
	"\x10SCRIPT_TIMED_OUT\x10\x03\x12\x1a\n" +
	"\x16UNHANDLED_SCRIPT_ERROR\x10\x042\xaa\x01\n" +
	"\x0fSnapshotService\x12F\n" +
	"\x10CreateConnection\x12\x15.cloud.vmm.GuestReady\x1a\x17.cloud.vmm.GuestMessage\"\x000\x01\x12O\n" +
	"\x18HandleResponsesFromGuest\x12\x1b.cloud.vmm.SnapshotResponse\x1a\x14.cloud.vmm.ServerAck\"\x00B\fZ\n" +
	"/cloud_vmmb\x06proto3"

var (
	file_snapshot_service_proto_rawDescOnce sync.Once
	file_snapshot_service_proto_rawDescData []byte
)

func file_snapshot_service_proto_rawDescGZIP() []byte {
	file_snapshot_service_proto_rawDescOnce.Do(func() {
		file_snapshot_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_service_proto_rawDesc), len(file_snapshot_service_proto_rawDesc)))
	})
	return file_snapshot_service_proto_rawDescData
}

var file_snapshot_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_snapshot_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_snapshot_service_proto_goTypes = []any{
	(OperationType)(0),       // 0: cloud.vmm.OperationType
	(SupportedFeatures)(0),   // 1: cloud.vmm.SupportedFeatures
	(AgentErrorCode)(0),      // 2: cloud.vmm.AgentErrorCode
	(*SnapshotRequest)(nil),  // 3: cloud.vmm.SnapshotRequest
	(*ServerInfo)(nil),       // 4: cloud.vmm.ServerInfo
	(*SnapshotResponse)(nil), // 5: cloud.vmm.SnapshotResponse
	(*GuestReady)(nil),       // 6: cloud.vmm.GuestReady
	(*GuestMessage)(nil),     // 7: cloud.vmm.GuestMessage
	(*ServerAck)(nil),        // 8: cloud.vmm.ServerAck
}
var file_snapshot_service_proto_depIdxs = []int32{
	0, // 0: cloud.vmm.SnapshotRequest.type:type_name -> cloud.vmm.OperationType
	1, // 1: cloud.vmm.ServerInfo.supported_features:type_name -> cloud.vmm.SupportedFeatures
	2, // 2: cloud.vmm.SnapshotResponse.agent_return_code:type_name -> cloud.vmm.AgentErrorCode
	0, // 3: cloud.vmm.SnapshotResponse.type:type_name -> cloud.vmm.OperationType
	3, // 4: cloud.vmm.GuestMessage.snapshot_request:type_name -> cloud.vmm.SnapshotRequest
	4, // 5: cloud.vmm.GuestMessage.server_info:type_name -> cloud.vmm.ServerInfo
	6, // 6: cloud.vmm.SnapshotService.CreateConnection:input_type -> cloud.vmm.GuestReady
	5, // 7: cloud.vmm.SnapshotService.HandleResponsesFromGuest:input_type -> cloud.vmm.SnapshotResponse
	7, // 8: cloud.vmm.SnapshotService.CreateConnection:output_type -> cloud.vmm.GuestMessage
	8, // 9: cloud.vmm.SnapshotService.HandleResponsesFromGuest:output_type -> cloud.vmm.ServerAck
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_snapshot_service_proto_init() }
func file_snapshot_service_proto_init() {
	if File_snapshot_service_proto != nil {
		return
	}
	file_snapshot_service_proto_msgTypes[4].OneofWrappers = []any{
		(*GuestMessage_SnapshotRequest)(nil),
		(*GuestMessage_ServerInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_service_proto_rawDesc), len(file_snapshot_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snapshot_service_proto_goTypes,
		DependencyIndexes: file_snapshot_service_proto_depIdxs,
		EnumInfos:         file_snapshot_service_proto_enumTypes,
		MessageInfos:      file_snapshot_service_proto_msgTypes,
	}.Build()
	File_snapshot_service_proto = out.File
	file_snapshot_service_proto_goTypes = nil
	file_snapshot_service_proto_depIdxs = nil
}
